/**
 * Created by sergiosantamaria on 5/06/16.
 */
var languajeCT = {
  'menu': {
    'ini': "Inici",
    'pro': "Pròleg",
    'rita': "Rita Montaner",
    'carmen': "Carmen Castillo",
    'lorraine': "Lorraine Allen",
    'abbe': "Abbe Lane",
    'charo': "Charo Baeza",
    'epi': "Epíleg",
    'credits': "Crèdits",
    'doculineal': "Veure el documental complet"
  },
  'CatText': {
    'cita11': "De Girona recordo molt poc, si no és la intimitat d’aquella plaça on passava llargues hores del dia i que em semblava meva.",
    'cita12': "Vaig desembarcar en aquella ciutat portentosa sense ni cinc a la butxaca i sense parlar ni una paraula d'anglès.",
    'cita12Plus': "Finalment va venir el moment que vaig creure posseir els diners suficients per emprendre aquell viatge somiat i a Nova York me'n vaig anar amb el meu violí sota el braç, embolicat en una funda que em va fer la meva mare perquè no teníem prou diners per comprar un estoig.",
    'cita14': "Era indispensable ampliar els meus estudis i assistir a les escoles musicals més acreditades de l’època que es trobaven a Berlín.",
    'cita15': "Vaig arribar a Hollywood quan tenia 18 anys.",
    'cita21': "Va ser en aquesta època quan va néixer en mi el sentiment de l'amor. El nom de la meva enamorada era Rita Montaner, un cubana de pare català. ",
    'cita21Plus': "Era una autèntica estàtua de banús clar i les seves línies corporals tenien la perfecció d'una obra d'art. Ens vam conèixer quan érem nens. Ella tenia els mateixos anys que jo. Estudiava com jo al Conservatori Peyrellada de l'Havana: ella el piano i jo el violí. Vam fer alguns concerts conjuntament. Artista polifacètica i mite cubà, Montaner és pianista i antiga condeixeble a l'Havana, i durant tres anys viatgen i actuen pel vell continent.",
    'cita41':"“El nostre matrimoni només va durar tres anys.",
    'cita41Plus': "Com totes les grans models, va arribar a percebre un sou fenomenal per hora: 500$; dòlars de llavors... Va signar un contracte exclusiu per presentar el perfum... a la televisió. Un matrimoni entre un director d'orquestra i una model exuberant no pot durar molt de temps, ja que mentre ella estava a Chicago, literalment envoltada d'admiradors, jo tocava a Manila envoltat d'unes filipines angèliques.",
    'cita41Post': "Al final ens vàrem divorciar, molt feliços i molt amics, fins avui.",
    'cita42': "És així que jo em vaig convertir també en una 'estrella' del cinema i que es van fer algunes pel·lícules de les quals el protagonista bàsic i fonamental era Cugat i els seus nois.",
    'cita42Plus': "Jo vaig viure el temps en què el cinema es basava sobretot en l'actor o l'actriu. S'anava a veure una pel·lícula de Charles Chaplin, de Pola Negri o de Greta Garbo. A ningú li interessava l'argument i ni sabien el nom del director. Els empresaris es dirigien a un bon professional i li deien simplement: 'Escriu-me un argument en què càpiguen tal i tal artista'. El mateix es feia en les pel·lícules musicals. Tot girava al voltant de Fred Astaire, Gene Kelly i el director de les orquestres que formaven l'espectacle.",
    'cita51':"Abbe Lane ha estat la dona que més ha influït en la meva vida. No és d'estranyar, va ser la que més vaig estimar",
    'cita51Plus': "i la que va estar amb mi més temps: 15 anys és tota una vida artística. Jo no sé fins a quin punt el meu amor de marit per ella tenia també una mica de paternal. Tinguem en compte la diferència d'edat i de condició. Quan jo la vaig descobrir era una simple dansaire de cabaret, molt bella, però artísticament només sabia aixecar les cames en aquells ballets mecànics creats per les famosos “Rockettes” del Radio City Hall. Jo la vaig interessar en el cant i en balls més sofisticats: vaig ser com un escultor que anava aixecant cada dia una estàtua més completa i atractiva: el seu marit, el seu pare i el seu creador artístic.",
    'cita52':"",
    'cita52Plus': "",
    'cita53':"Vam recórrer el món sencer. Amb ella vaig inaugurar un dels espectacles de Las Vegas.",
    'cita53Plus': "Va passar amb ella el mateix que amb les altres: quan va arribar a tenir un nom per si mateixa, es va separar del meu espectacle i va volar amb les seves pròpies ales.",
    'cita56': "Ara que ja he introduit la rumba al mercat nord-americà, la meva intenció és introduir la sardana”.",
    'cita60': "Jo estava buscant una artista pel meu espectacle. Charo cantava i va ballar millor del que jo creia i vaig veure que tenia un excel·lent tipus per atraure els públics nord-americans. Necessitava però ser preparada.",
    'cita61':"Charo Baeza ha estat, amb Abbe Lane, l'artista i l'esposa que m'han donat més satisfaccions sentimentals i artístiques.",
    'cita61Plus': "Ara bé, Abbe Lane només era apreciada pels homes; Charo, en canvi, ha caigut molt bé als homes i als nens nord-americans. Ha sortit una nina que és el seu efígie. Es venen milions d'exemplars i Charo té una comissió. Tant ella com Abbe Lane eren dues dones posseïdores d'aquest 'sexy' tan misteriós.",
    'cita62':"El que m’interessa és adquirir alguna cosa feta,",
    'cita62Plus': " o sino un terreny situat en una muntanya, prou elevada perquè ningú li tregui la vista. Jo només vull un estudi amb bany, així doncs no crec que sigui gaire difícil trobar un petit terreny i jo m’hi edificaré un estudi. En el futur penso passar moltes temporades a la cosa Brava pintant i el que necessito és alguna cosa còmoda amb molta llum i que estigui situada en un lloc que no sigui trist ni amagat.",
    'cita62Post': "No espero ni vull un palau, només un lloc per treballar i per sortir d’aquest Beverly Hills que ja no aguanto.",
    'cita63':"",
    'cita63Plus': "",
    'cita100':"Durant setmanes senceres vaig tractar inútilment de tenir una cita amb Carmen. Quan li demanava el seu número de telèfon em donava números falsos.",
    'cita100Plus': "Li vaig demanar quina era l'estranya raó de la seva conducta. Carmen em va explicar que en el fons del seu cor creia que si continuaven les nostres relacions culminarien en matrimoni i ella no estava disposada a abandonar la seva carrera. La seva resposta em va produir angoixa ja que no sabia encara que em trobava davant d'uns éssers humans, els actors i actrius de Hollywood, la preocupació exclusiva dels quals era la seva pròpia carrera artística. Però, així i tot, em vaig dir a mi mateix: em casaré amb aquesta noia."
  },
'photoText': {
  'prel03': "“Confesso una certa nostàlgia cap a aquella plaça de l'Oli on vaig néixer, i no em fa vergonya dir que rebria amb gran plaer la notícia que l'ajuntament posés una placa, per petita i discreta que sigui, a la façana de la casa on la meva mare em va parir. Això em faria feliç, perquè sense ella sóc un arbre amb moltes branques sense cap arrel concreta.”",
  'prel02': "En aquesta casa hi nasqué Xavier Cugat i Mingall (1900-1990), músic i intèrpret cinematogràfic",
  'prel04': "Joan Cugat de Bru era un electricista amb problemes per idees progressistes i republicanes a l'Espanya de principis del segle XX. Al costat de la seva dona, la modista, Àvila Mingall, els seus quatre fills Francesc, Albert, Xavier i Enric, i la seva cunyada i el seu sogre, va emprendre un llarg viatge cap a les Amèriques.",
  'prol01': "El gran tenor Enrico Caruso estava assegut al cafè Gómez, un bar de l'Havana, reposant de la calor a l'ombra i dibuixant caricatures, la seva gran afició. A Caruso li va fer gràcia el dibuix que el joveníssim Cugat li havia fet i el va convidar a un refresc, i així va començar una amistat que marcaria per sempre la vida de Cugat...",
  'prol01b':"Animat per Caruso, el 1912 marxa a fer fortuna a Nova York.",
  'prol02': "El prestigiós conservatori Peyrellada de l'Havana li va obrir les portes per estudiar violí de molt jove, amb Joaquín Molina, director de l'orquestra Nacional de Cuba. El 1910, un joveníssim Cugat comença a tocar a l'Orquestra Simfònica del Teatre Nacional de Cuba i coneix al gran tenor del moment, Enrico Caruso.",
  'prol03': "La màgica nit de Reis de 1906, el veí li va fer un violí a la seva mida. Ja no va deixar l'instrument. El pare li va recomanar que deixés d'anar a estudi i es dediqués a la música. Així començava la carrera de qui es convertiria en un mite, músic, compositor, director i productor que triomfaria en els anys daurats de Hollywood amb la música llatina, que va popularitzar a tot el món.",
  'prol05': "Agustí Borgunyó era un pianista que havia arribat a Nova York en una situació precària semblant a la de Cugat. La fortuna feu que les seves vides s'entrecreuessin en un duo musical de supervivència i junts arribaren a tocar al Carnegie Hall i el Metropolitan Opera, dos prestigiosos salons de Nova York.",
  'prol05b': "Finalment un petit restaurant proper al Carnegie Hall els va donar feina. Era el centre de trobada de cantants. Allà van conèixer Maria Gay i Enric Granados. Nous aires arribaven per Cugat i Borgunyó a la ciutat dels gratacels...",
  'prol06': "Entre 1915 i 1918, Cugat lidera la seva primera formació musical a Nova York, obrint-se així un buit en l'escena musical de la ciutat. A continuació, iniciaria el seu periple amorós amb Rita Montaner.",
  'rm11': "Artista polifacètica i mite cubà, Montaner és pianista i antiga condiscípula a l'Havana, i durant tres anys viatgen i actuen pel vell continent.",
  'rm12': "Rita Montaner va ser la seva primera dona, cantant cubana d'ascendència catalana, amb la qual es va casar recentment complerta la majoria d'edat.",
  'rm13': "Ella es va convertir en una estrella del xou musical i va ser la primera persona a qui Xavier Cugat va ajudar a arribar a la fama. La primera d'una llarga llista de dones que sempre l'acabaven abandonant, però per a les que no sentia cap ressentiment. Cugat es veia com l'escultor que modula, amb dedicació i bon criteri, les possibilitats artístiques d'una joia en brut.",
  'rm17': "Quan vaig conèixer Charles Chaplin era l'artista i el còmic més famós del món. [...] Estava començant un nou film amb so i em va oferir un seguit de solos de violí per ser interpretats com a música de fons. [... ] Va ser el meu primer treball relacionat amb el cinema seguit per altres sempre sol·licitats per Chaplin. [...] No obstant això, d'altra banda s'iniciava l'era d'or del cinema musical: el doblatge en música de l'acció en l'escena, tal com jo vaig fer amb Chaplin. No exageraré la nota si dic que històricament vàrem ser Chaplin i jo, en aquest ordre, els interlocutors de les pel·lícules amb música gravada.",
  'rm16': "El 1921 participa en la seva primera gran producció de Hollywood, 'Els quatre genets de l'Apocalipsi', de Rex Ingram, una pel·lícula muda on apareix Cugat i el seu violí. Rodolfo Valentino protagonitza la pel·lícula i conèixer-lo li obre les portes de Hollywood de bat a bat.",
  'rm18': "Abadal havia de tornar a Barcelona i va proposar a Cugat com a intermediador per vendre els seus objectes, de manera que el jove Cugat aviat es va trobar instal·lat a la ciutat del cinema envoltat de quadres originals dels clàssics espanyols. Van assistir a la inauguració personalitats de la talla de Charles Chaplin o Douglas Fairbanks. Les caricatures de Cugat s'exposaven de pas en l'avantsala de l'exposició, per les quals es va interessar Charles Chaplin i el diari de la ciutat, Los Angeles Times, que li va proposar ser el seu caricaturista especialitzat en els personatges de Hollywood.",
  'rm15': "En una ocasió, el director del diari em va encarregar una caricatura de Valentino que estava rodant el famós film “Els quatre genets de l'Apocalipsi” de Vicent Blasco Ibáñez. Li vaig fer una caricatura que li va agradar molt i ens vam fer amics. Em va dir: “Home, Cugat!, sé que vostè és músic, per què no organitza vostè un grup de músics que toquin per a mi encara que la meva pel·lícula sigui silenciosa, per donar una mica d'ambient en el moment en què ballo un tango a “Els quatre genets”?",
  'cc31': "El salt definitiu a la direcció d'orquestres de ball el va fer de la mà de la seva segona esposa, Carmen Castillo, amb la qual es va casar l'any 1928.",
  'cc33a': "El  1930, a Tijuana es fixa amb una cantant i actriu jove, Rita Cansino. Cugat la va batejar com",
  'cc33b': " i la va catapultar a la fama mundial.",
  'cc35': "Començava ja el capítol de les pel·lícules parlades. La Warner Brothers, llavors una modesta empresa, va fer un primer assaig amb la meva orquestra i amb un tenor del Metropolitan anomenat Giovanni Martinelli. Van ser només dos curts d'una mitja hora. La filmació tenia de ser contínua, sense cap tall. Encara no existia el gravat en film, sinó en disc. El curt es va anomenar “Xavier Cugat i els seus gigolós”. Puc dir que la primera pel·lícula sonora de la història del cinema porta imprès el meu nom i la meva orquestra.",
  'cc36': "El 1930, a Tijuana es fixa amb una cantant i actriu jove, Rita Cansino. Cugat la va batejar com Rita Hayworth i la va catapultar a la fama mundial.",
  'cc38': "A partir de 1929 va començar amb una afició que va durar 70 anys: aconseguir fotografies signades per tots els presidents dels Estats Units: Herbert Hoover, Harry Truman, Dwight Eisenhower, John Fitzgerald Kennedy, Lyndon B. Johnson, Richard Nixon, Gerald Ford i Ronald Reagan.",
  'cc39': "El 1931 ajuda amb la banda sonora de 'Llums de la ciutat', de Charles Chaplin.",
  'la2': "Al voltant de l'època en què es varen produir les grans pel·lícules musicals, Cugat va compartir alguns anys de la seva vida amb una model de Chicago: Lorraine Allen.",
  'la5': "cartell de 'Escuela de sirenas', George Sidney, 1944.",
  'la4a': "Durant els anys 40 Cugat participa en nombrosos musicals, essent ‘Escola de Sirenes’ el de més èxit.",
  'la4b': "Altres títols varen ser ‘Ballant neix l’amor’, de William A. Seiter; ‘Tres dies d’amor i fe’, de Frank Borzage; ‘Dues noies i un mariner‘, de Ricahrd Thorpe; ‘Cap de setmana’, de Robert Z. Leonard; ‘Festival a Mèxic’, de George Sidney; ’El record dels teus llavis’, de Ricahrd Thorpe i ‘La filla de Neptú’, d’Edward Buzzell.",
  'la9': "L'any 1945 Cugat i Frank Sinatra varem gravar un senzill amb un parell de boleros lents: 'My Shawl' i 'Stars in your eyes'.",
  'la8': "Altre cartell de 'Escuela de sirenas', George Sidney, 1944.",
  'la10': 'cartell de"En una isla contigo". Richard Thorpe, 1948.',
  'la6': "L'any 1940 va enregistrar la cançó 'Perfídia', que va esdevenir un gran èxit, amb el cantant Miguelito Valdés.",
  'al12': "Quan es va casar per quarta vegada, Cugat tenia ja 52 anys i ella 20. El veritable nom d'Abbe Lane era Abigale Lasman, filla d'un matrimoni hebreu. Cugat la va rebatejar com Abbe Lane.",
  'al23': "Tenia una gran personalitat i malgrat no haver tingut sang llatina, a Itàlia la van anomenar 'la regina del txa txa txa'. Era bonica, amb sexe i simpatia.",
  'al24': "La seva família era molt modesta, gairebé pobra. Els pares, ella i el seu germà, dormien en una sola habitació. La vaig començar a vestir al meu gust i va anar progressant amb gran rapidesa.",
  'al26': "Avui s'acosta als 50 (actualment, Abbe Lane té 83 anys) i guanya de 35.000 a 40.000 dòlars a la setmana a Las Vegas, encara amb el nom que va adquirir viatjant com rodamón per totes les terres amb el meu espectacle.",
  'al27': "En aquest punt de la vida, Cugat era considerat el rei de la rumba i de la samba per tot arreu. Havia arribat al cim de la seva professió i va deixar participar a Abbe Lane dels seus èxits. Abbe Lane va tastar, de la ma de Cugat, el xampany, el caviar i els avions per primera vegada.",
  'al28': "Va arribar a ser una veritable estrella: cantava molt bé, amb molt i estil i gràcia.",
  'al25': "En aquest punt de la vida, Cugat era considerat el rei de la rumba i de la samba per tot arreu. Havia arribat al cim de la seva professió i va deixar participar a Abbe Lane dels seus èxits.",
  'al31': "El 1954, el gran moment a Espanya per Cugat arriba: debuta amb la seva orquestra a la Plaça Monumental de Barcelona.",
  'al33': "“Cugat y Abbe en Barcelona”. “Amb un pes de 53 kg harmoniosament distribuïts…” - sobre Abbe Lane, que acompanyava Cugat - Premsa de l'època",
  'al35': "“L'aeroport semblava un eixam amb tanta vespa”, fans a la seva rebudaen la seva gira per Espanya. Premsa de l'època.”",
  'cb01': "“El meu amor paternal va anar canviant amb el temps.Més crescudeta era ja una dona i podia molt bé ser la meva dona. Va ser així que ens vam casar. Aquella murcianeta tímida i juvenil es va transformar en una veritable estrella de l'espectacle nord- americà. És la meva Charo, el meu últim descobriment i l'última dona de la meva vida”.",
  'cb11': "“La noia tenia veritablement un gran talent natural i una gran ambició artística. Va progressar amb una rapidesa indiscutible. Quan la vaig conèixer acabava de sortir d'una escola de Múrcia; les dues germanes estaven tancades en un convent de monges”.",
  'cb15': "“Li vaig proposar que vingués amb mi als EUA acompanyada de la seva germana. Em van assegurar que eren majors d'edat, però després vaig saber que no era així. Una d'elles treballava com a maquilladora en els teatres. El primer que vaig fer en arribar als EUA va ser donar­li un professor d'anglès, una mestra de cant i després una altra de ball i que a poc a poc veiés com són els espectacles dels EUA”.",
  'cb04': "Cugat s’emporta a Charo a treballar als Estats Units, i finalment, l'any 1966 es casa amb ella, el seu cinquè i últim matrimoni.",
  'cb09': "L'any 1971 torna a Catalunya i el seu ideal era tenir una casa estudi a la Costa Brava on poder mirar el mar i dibuixar.",
  'cb09b': "Retrat de Xavier Cugat realitzat per Manuel Pérez Sanjulián.",
  'cb21': "Algunes de les obres de Xavier Cugat."
},
'tooltipText': {
  'text1': "La màgica nit de Reis d'aquell any, el veí li va fer un violí a la seva mida. Ja no va deixar l'instrument. El pare li va recomanar que deixés d'anar a estudiar i es dediqués a la música. Així començava la carrera de qui es convertiria en un mite, músic, compositor, director i productor que triomfaria en els anys daurats de Hollywood amb la música llatina, que va popularitzar a tot el món.",
  'text2a': "Cugat se'n va a estudiar a Alemanya, a Berlín, per perfeccionar la seva tècnica, i els seus pares tornen a Espanya i s'instal·len a la Bisbal d'Empordà, Girona, adquirint una granja de pollastres.",
  'text2b': "El gran somni de Cugat era esdevenir un gran concertista clàssic. No ho va aconseguir però sí que va aconseguir l'anomenat 'Somni americà'.",
  'text3': "'Va ser també durant aquests temps quan va aconseguir gran fama a Tijuana en la frontera de Mèxic i la Baixa Califòrnia un club nocturn, que era també casino de joc i hipòdrom. Jo era l'espectacle principal i tenia una parella que aviat es va imposar a l'atenció del públic. Paradoxalment estava formada per un pare i la seva filla, excel·lents ballarins espanyols. La filla es deia Rita, tenia 17 anys, de formes proporcionades i harmòniques'.",
  'text4': "L'any 1946 Cugat va guanyar un milió de dòlars com a director d’orquestra. En aquell moment, era el màxim salari guanyat mai per un director d’orquestra. Equivalent a guanyar en l'actualitat 12 milions de dòlars",
  'text5': "'Divorciat de Lorrain Allen, necessitava una nova companya, tant per a la meva vida privada com per a al meu espectacle. En la meva recerca d'una noia que complís els requisits necessaris, vaig anar a Nova York a veure l'espectacle produït per l'ex marit de Liz Taylor, el productor Michael Todd. L'espectacle es deia 'Botton Shoes'. En el cor hi havia setze noies ballant, totes molt belles i molt semblants. Però vaig creure que la cinquena per l'esquerra tenia 'un no sé què' diferent. M'agradaria conèixer a aquesta noia. Vaig fer que em presentessin a ella[...] Es deia Abbe Lane. El 1950 ens vam casar i vam ser feliços durant quinze anys de matrimoni'."
},
'text': {
  'mainTitle': "SEXE, MARAQUES I CHIHUAHUES",
  'mainSubtitle': "La increïble vida de",
  'name': "Xavier Cugat",
  'instructionAnecdota': "Fes clic quan vegis aparèixer al chihuahua, podràs conèixer tot tipus d'anècdotes curioses sobre Cugui",
  'instructionPentagram': "Fes clic sobre les notes musicals per recórrer la vida d'en Xavier, des de la seva infància fins a la seva vellesa",
  'instructionLastVideos': "Fes scroll per descobrir més vídeos sobre Xavier Cugat del fons documental de TV3",
  'instructionInfo': "Fes clic aquí per conèixer més detalls sobre un moment en particular de la vida de Cugat",
  'mobileDisclaimer': "Malauradament, aquest documental interactiu no està dissenyat per a dispositius mòbils. Gaudeix millor de l'univers de Xavier Cugat des del teu ordinador o tablet. T'esperem!",
  'texto11': "Xavier Cugat va néixer a Girona l'1 de gener de 1900.",
  'text1': "Entre 1915 y 1918  lidera su primera formación musical y empieza su periplo amoroso con su primera mujer: RITA MONTANER",
  'text2': "L'any 1945 Cugat i Frank Sinatra varem gravar un senzill amb un parell de boleros lents: 'My Shawl' i 'Stars in your eyes'",
  'text4': "Cugat se lleva a Charo a trabajar a Estados Unidos y, finalment, l'any 1966 es casa amb ella, el seu cinquè i últim matrimoni.",
  'text5': "El 1954, Cugat debuta amb la seva orquestra a la Plaça Monumental de Barcelona.",
  'text6': "Descubridor de Rita Hayworth",
  'text7': "L'any 1971 torna a Catalunya i el seu ideal era tenir una casa estudi a la Costa Brava on poder mirar el mar i dibuixar.",
  'textoFin': "Cugat va morir a Barcelona el 27 d'octubre de 1990."
}
};
