/**
 * Created by sergiosantamaria on 5/06/16.
 */
var languajeSP = {
  'menu': {
   'ini': "Inicio",
   'pro': "Prólogo",
   'rita': "Rita Montaner",
   'carmen': "Carmen Castillo",
   'lorraine': "Lorraine Allen",
   'abbe': "Abbe Lane",
   'charo': "Charo Baeza",
   'epi': "Epílogo",
   'credits': "Créditos",
   'doculineal': "Ver el documental completo"
 },
 'CatText': {
   'cita11': "De Girona recuerdo muy poco, excepto la intimidad de aquella plaza donde pasaba largas horas y que se me antojaba mía.",
   'cita12': "Desembarqué en aquella ciudad portentosa sin un duro en el bolsillo y sin hablar una palabra de inglés.",
   'cita12Plus': "Finalmente, llegó el momento en el que creí tener el dinero suficiente para emprender aquel viaje soñado, y a Nueva York me fui con el violín bajo el brazo, envuelto en una funda que me hizo mi madre porque no tenía dinero para comprar un estuche.",
   'cita14': "Era indispensable ampliar mis estudios y asistir a las escuelas musicales más acreditadas de la época, que se encontraban en Berlín.",
   'cita15': "Llegué a Hollywood cuando tenía 18 años.",
   'cita21': "Fue en esta época cuando nació en mí el sentimiento del amor. El nombre de mi enamorada era Rita Montaner, una cubana de padre catalán.",
   'cita21Plus': "Era una auténtica estatua de ébano claro y sus líneas corporales tenían la perfección de una obra de arte. Nos conocimos cuando éramos unos niños, ella tenía los mismos años que yo. Estudiaba, como yo, en el Conservatorio Peyrellada de La Habana: ella, el piano y yo, el violín. Hicimos algunos conciertos juntos.",
   'cita41':"Nuestro matrimonio solo duró tres años.",
   'cita41Plus': "Como todas las grandes modelos, llegó a percibir un sueldo fenomenal por hora: 500 dólares de la época… Un matrimonio entre un director de orquesta y una modelo exhuberante no podía durar mucho tiempo; mientras ella estaba en Chicago, rodeada literalmente de admiradores, yo tocaba en Manila rodeado de angélicas filipinas.",
   'cita41Post': "Al final nos divorciamos, muy felices y muy amigos, hasta hoy.",
   'cita42': "Así fue como me convertí yo también en una estrella de cine y se hicieron algunas películas en las que el protagonista básico y fundamental era Cugat y sus muchachos.",
   'cita42Plus': "Yo viví la época en la que el cine se basaba, sobre todo, en los actores y actrices. Se iba a ver una película de Charles Chaplin, de Pola Negri o de Greta Garbo, a nadie le interesaba el argumento y ni sabían el nombre del director. Los empresarios se dirigían a un buen profesional y le decían, simplemente: ‘Escríbeme un guión en el que quepan tal y cual artista’. Lo mismo ocurría con las películas musicales: todo giraba alrededor de Fred Astaire, Gene Kelly y el director de la orquesta que formaba el espectáculo.",
   'cita51':"Abbe Lane ha sido la mujer que más ha influido en mi vida. No es de extrañar, ya que fue a la que más amé",
   'cita51Plus': "y la que estuvo conmigo más tiempo: 15 años es toda una vida artística. No sé hasta qué punto mi amor de marido por ella tenía también algo de paternal, tengamos en cuenta la diferencia de edad y de condición. Cuando la descubrí era una simple bailarina de cabaret: muy bella, pero artísticamente solo sabía levantar las piernas en aquellos bailes mecánicos creados por las famosas ‘Rockettes’ del Radio City Hall. Yo hice que se interesara por el canto y por bailes más sofisticados: fui como un escultor que cada día iba formando una estatua más compleja y atractiva. Fui su marido, su padre y su creador artístico.",
   'cita52':"",
   'cita52Plus': "",
   'cita53':"Recorrimos el mundo entero, con ella inauguré uno de los espectáculos de Las Vegas.",
   'cita53Plus': "Ocurrió con ella lo mismo que con otras: cuando llegó a tener un nombre por sí misma, se separó de mi espectáculo y voló con sus propias alas.",
   'cita56': "Ahora que ya he introducido la rumba en el mercado norteamericano, mi intención es introducir la sardana.",
   'cita60': "Yo estaba buscando una artista para mi espectáculo. Charo cantaba y bailaba mejor de lo que me esperaba y vi que tenía un tipo excelente para atraer al público norteamericano. Necesitaba, sin embargo, que la preparasen.",
   'cita61':"Charo Baeza ha sido, junto con Abbe Lane, la artista y esposa que más satisfacciones sentimentales y artísticas me ha dado.",
   'cita61Plus': "Ahora bien, Abbe Lane solo fue apreciada por los hombres; Charo, en cambio, cayó muy bien tanto a los hombres como a los niños norteamericanos: se puso a la venta una muñeca con su imagen, se vendieron millones de ejemplares y Charo se llevó una comisión. Tanto ella como Abbe Lane poseían ese ‘sexy’ tan misterioso.",
   'cita62':"Me interesa comprar algo ya edificado.",
   'cita62Plus': "O, si no, un terreno situado en una montaña bastante elevada para que nada le tape las vistas. Solo quiero un estudio con baño, así que no creo que sea muy difícil encontrar un pequeño terreno y construirme un estudio. Pienso pasar en el futuro muchas temporadas en la Costa Brava pintando y lo que necesito es algo cómodo, con mucha luz y que esté situado en un lugar que no sea triste ni esté escondido.",
   'cita62Post': "No quiero ni espero un palacio, solo un lugar para trabajar y salir de este Beverly Hills que ya no soporto.",
   'cita63':"",
   'cita63Plus': "",
   'cita100': "Durante semanas enteras traté inútilmente de conseguir una cita con Carmen. Cuando le pedía el teléfono, me daba números falsos.",
   'cita100Plus': "Le pregunté cuál era la razón de su comportamiento: Carmen me explicó que, en el fondo de su corazón, creía que si nuestra relación continuaba terminaría en matrimonio, y ella no estaba dispuesta a abandonar su carrera. Su respuesta me produjo angustia, pues todavía no sabía que me encontraba ante uno de esos seres humanos, los actores y actrices de Hollywood, cuya preocupación exclusiva era su propia carrera artística. Aún así, me dije: me casaré con esta muchacha."
 },
'photoText': {
 'prel03': "“Confieso que siento cierta nostalgia hacia aquella Plaza del aceite donde nací y no me avergüenza reconocer que recibiría con gran placer la noticia de que el Ayuntamiento pusiera una placa, por pequeña y discreta que sea, en la fachada de la casa donde mi madre me parió. Eso me haría feliz porque sin ella soy un árbol con muchas ramas, pero ninguna raíz.”",
 'prel02': "En esta casa nació Xavier Cugat i Mingall (1900-1990), músico e intérprete cinematográfico",
 'prel04': "Joan Cugat de Bru era un electricista con problemas por sus ideas progresistas y republicanas en la España de principios de siglo XX. Emigró a las Américas junto a su mujer, la modista Ávila Mingall, sus cuatro hijos (Francesc, Albert, Xavier y Enric), su cuñada y su suegro.",
 'prol01': "El gran tenor Enrico Caruso estaba sentado en el Café Gómez, un bar de La Habana, reponiéndose en la sombra del calor y dibujando caricaturas, su gran afición. A Caruso le hizo gracia el retrato que el pequeño Xavier le había hecho y le invitó a un refresco. Así comenzó una amistad que marcaría para siempre la vida de Cugat.",
 'prol01b':"Animado por Caruso, en 1912 se marcha a buscar fortuna a Nueva York.",
 'prol02': "El prestigioso conservatorio Peyrellada de La Habana para estudiar violín de la mano de Joaquín Molina, director de la Orquesta Nacional de Cuba. En 1910, un jovencísimo Cugat comienza a tocar en la Orquesta Sinfónica del Teatro Nacional de Cuba y conoce al gran tenor del momento, Enrico Caruso.",
 'prol03': "Para la mágica noche de reyes de 1906, el vecino le hizo un violín a su medida: desde entonces, ya no abandonaría el insturmento. Su padre le recomendó que dejara los estudios y se dedicara a la música; así comenzó la carrera de quien se convertiría en un mito: músico, compositor, director y productor que triunfaría en los años dorados de Hollywood con la música latina, que popularizó en todo el mundo.",
 'prol05': "Agustí Borgunyó era un pianista que había llegado a Nueva York en una situación precaria, parecida a la de Cugat. La fortuna quiso que sus vidas se cruzaran en un dúo musical de supervivencia. Juntos llegaron a tocar en el Carnegie Hall y el Metropolitan Opera, dos prestigiosos salones de Nueva York.",
 'prol05b': "Finalmente, un pequeño restaurante cercano al Carnegie Hall les dio trabajo. Era un punto de encuentro de cantantes, allí conocieron a María Gay y Enrique Granados: soplaban vientos favorables para Cugat y Borgunyó en la ciudad de los rascacielos.",
 'prol06': "Entre 1915 y 1918, Cugat lidera su primera formación musical, un grupo de tangos, abriéndose así un hueco en la escena musical de la ciudad. Es entonces cuando empieza su periplo amoroso con Rita Montaner.",
 'rm11': "Artista polifacética y mito cubano, Montaner es pianista y antigua compañera de conservatorio en La Habana. Durante tres años viajan y actúan por Europa.",
 'rm12': "Rita Montaner es su primera mujer. Cantante cubana de ascendencia catalana, se casó con ella nada más alcanzar la mayoría de edad.",
 'rm13': "Ella se convirtió en una estrella del show musical y fue la primera persona a la que Xavier Cugat ayudó a llegar a la fama. La primera de una serie de mujeres que siempre terminaban separadas de él, pero a las que no guardaba ningún resentimiento. Cugat se veía como un escultor que moldea, con dedicación y buen criterio, las posibilidades artísticas de una joya en bruto.",
 'rm17': "Cuando conocí a Charles Chaplin, él era el artista y cómico más famoso del mundo. [...] Él estaba realizando un nuevo film con sonido y me ofreció una serie de solos de violín para ser interpretados como música de fondo. [...] Fue mi primer trabajo relacionado con el cine, seguido por otros, siempre por petición de Chaplin. [...] Por otro lado, comenzaba la edad de oro del cine musical: con el doblaje de la música que se veía en escena, tal y como yo hice con Chaplin. No exagero si digo que, históricamente, fuimos Chaplin y yo, en este orden, los inventores de las películas con música grabada.",
 'rm16': "En 1921 participa en su primera gran producción de Hollywood, ‘Los cuatro jinetes del Apocalipsis’, de Rex Ingram, una película muda donde aparece Cugat con su violín.",
 'rm16b': "Rodolfo Valentino protagoniza la película, y conocerle le abre a Cugat las puertas de Hollywood de par en par.",
 'rm18': "Abadal tenía que volver a Barcelona y propuso a Cugat que hiciera de intermediador para vender sus objetos, por lo que el joven Cugat se vio instalado en la meca del cine, rodeado de lienzos. A la inauguración de la galería asistieron personalidades de la talla de Charles Chaplin o Douglas Fairbanks. Las caricaturas de Cugat, expuestas en la antesala, despertaron el interés del diario Los Angeles Times, que propuso a Cugat ser su caricaturista especializado en los personajes de Hollywood.",
 'rm15': "“En una ocasión, el director del periódico me encargó una caricatura de Valentino, que estaba rodando el famoso film ‘Los cuatro jinetes del Apocalipsis’, basado en la novela de Vicente Blasco Ibáñez. Realicé una caricatura que al propio Valentino le gustó mucho y nos hicimos amigos. Me dijo: “¡Hombre, Cugat! Sé que usted es músico, ¿por qué no organiza un grupo y toca para mí, aunque la película sea muda, para crear ambiente en la escena en la que bailo un tango en ‘Los cuatro jinetes…’?”",
 'cc31': "Fotografía firmada por Carmen Castillo en 1930",
 'cc32': "Carmen Castillo con el pequeño 'Lobo'",
 'cc34': "El salto definitivo a la dirección de orquestas de baile lo hará de la mano de su segunda esposa, Carmen Castillo, con la que se casó en 1928.",
 'cc33a': "En 1930, en Tijuana, Cugat se fija en una joven cantante y actriz, Margarita Cansino. Cugat siempre contó que la bautizó como",
 'cc33b': " y que contribuyó a catapultarla a la fama.",
 'cc35': "En esa época comenzaba el capítulo de las películas habladas. La Warner Brothers, entonces una empresa modesta, hizo un primer ensayo con mi orquesta y con un tenor del Metropolitan llamado Giovanni Martinelli. Fueron solo dos cortometrajes, de una media hora cada uno. La filmación tenía que ser continua, sin cortes; todavía no existía el grabado sonoro en film, sino que se realizaba sobre un disco. El corto se tituló ‘Xavier Cugat y sus gigolós’. Puedo afirmar que la primera película sonora de la historia del cine lleva impresa mi nombre y el de mi orquesta.",
 'cc36': "En 1930, en Tijuana, Cugat se fija en una joven cantante y actriz, Margarita Cansino. Cugat siempre contó que la bautizó como Rita Hayworth y que contribuyó a catapultarla a la fama.",
 'cc38': "A partir de 1929 comenzará una afición que durará 70 años: conseguir las fotografías firmadas de los presidentes de Estados Unidos: Herbert Hoover, Harry Truman, Dwight Eisenhower, John Fitzgerald Kennedy, Lyndon B. Johnson, Richard Nixon, Gerald Ford y Ronald Reagan.",
 'cc39': "En 1931 colabora en la banda sonora de 'Luces de la ciudad', de Charles Chaplin.",
 'la2': "Durante la época en la que se produjeron las grandes películas musicales, Cugat compartió unos años de su vida con una modelo de Chicago: Lorraine Allen.",
 'la5': "Cartel de 'Escuela de sirenas', George Sidney, 1944.",
 'la4a': "Durante los años 40, Cugat participa en numerosos musicales, entre los que ‘Escuela de sirenas’ fue el de mayor éxito.",
 'la4b': "Otros títulos fueron ‘Bailando nace el amor’, de William A. Seiter; ‘Tres días de amor y fe’, de Frank Borzage; ‘Dos novias para un marino‘, de Richard Thorpe; ‘Fin de semana’, de Robert Z. Leonard; ‘Festival en México’, de George Sidney; ’El recuerdo de tus labios’, de Richard Thorpe y ‘La hija de Neptuno’, de Edward Buzzell.",
 'la9': "En el año 1945, Cugat y Frank Sinatra graban un sencillo y dos boleros lentos: 'My Shawl' y 'Stars in your eyes'.",
 'la8': "Otro cartel de 'Escuela de sirenas', George Sidney, 1944.",
 'la10': 'Cartel de "En una isla contigo". Richard Thorpe, 1948.',
 'la6': "En 1940 graba, con el cantante Miguelito Valdés, la canción ‘Perfidia’, que se convertiría en un gran éxito.",
 'al12': "Cuando se casa por cuarta vez, Cugat ya tiene 52 años, mientras que ella tiene 20. Su verdadero nombre.",
 'al23': "“Abbe Lane tenía una gran personalidad. A pesar de no ser latina, en Italia la llamaban ‘la reina del cha-cha-chá’. Era bonita, sexy y simpática”.",
 'al24': "“Su familia era muy modesta, casi pobre. Los padres, su hermano y ella dormían en un solo cuarto. La empecé a vestir a mi gusto y fue progresando con gran rapidez”",
 'al26': "“Hoy se acerca a los 50 [actualmente, Abbe Lane tiene 83 años] y gana entre 35.000 y 40.000 dólares a la semana en Las Vegas, aún con el nombre que adquirió viajando como una trotamundos con mi espectáculo”.",
 'al27': "En aquel momento, Cugat era considerado el rey de la rumba y de la samba en todo el mundo. Había llegado a la cima de su profesión y dejó participar a Abbe Lane de su éxito. Abbe Lane probará, de la mano de Cugat, el champán y el caviar por primera vez.",
 'al28': "“Abbe Lane llegó a ser una verdadera estrella: cantaba muy bien, con mucho estilo y gracia”.",
 'al25': "En aquel momento, Cugat era considerado el rey de la rumba y de la samba en todo el mundo. Había llegado a la cima de su profesión y dejó participar a Abbe Lane de su éxito.",
 'al31': "En 1954 llega el gran momento de Cugat en España: debuta con su orquesta en la Plaza Monumental de Barcelona.",
 'al33': "‘Cugat y Abbe en Barcelona’. Sobre Abbe Lane, que acompañó a Cugat: ‘Con un peso de 53 kg armoniosamente distribuidos...’. Prensa de la época.",
 'al35': "“‘El aeropuerto parecía un enjambre con tanta Vespa.’ Fans en su recibimiento al aterrizar en Barcelona. Prensa de la época.”",
 'cb01': "“Mi amor paternal hacia ella fue cambiando con el tiempo. Más crecidita, Charo ya era una mujer y bien podía ser mi esposa, así que nos casamos. Aquella murcianita tímida y juvenil se transformó en una verdadera estrella del mundo del espectáculo en EE UU. Es mi Charo, mi último descubrimiento y la última esposa de mi vida”.",
 'cb11': "“La chica tenía verdaderamente un gran talento natural y una gran ambición artística, progresó con una rapidez indiscutible. Cuando la conocí, acababa de salir de la escuela, en Murcia. Ella y su hermana habían estado encerradas en un convento de monjas”.",
 'cb15': "“Le propuse que viniera conmigo a Estados Unidos, acompañada de su hermana. Me aseguraron que eran mayores de edad, pero después me enteré de que no era así. Lo primero que hice al llegar a los EE UU fue ponerle un profesor de inglés, una maestra de canto y otra de baile, e hice que poco a poco viera cómo eran los espectáculos allí”.",
 'cb04': "Cugat se lleva a Charo a trabajar a los Estados Unidos y, finalmente, se casa con ella en 1966. Sería su quinto y último matrimonio.",
 'cb09': "En 1971, Cugat regresa a Cataluña. Su proyecto era tener una casa-estudio en la Costa Brava para poder contemplar el mar y dibujar.",
 'cb09b': "Retrato de Xavier Cugat realizado por Manuel Pérez Sanjulián.",
 'cb21': "Algunas de las obras de Xavier Cugat."
},
'tooltipText': {
 'text1': "Para la mágica noche de reyes de 1906, el vecino le hizo un violín a su medida: desde entonces, ya no abandonaría el instrumento. Su padre le recomendó que dejara los estudios y se dedicara a la música; así comenzó la carrera de quien se convertiría en un mito: músico, compositor, director y productor que triunfaría en los años dorados de Hollywood con la música latina, que popularizó en todo el mundo.",
 'text2a': "Cugat se va a estudiar a Alemania, a Berlín, para perfeccionar su técnica. Mientras, sus padres vuelven a España y se instalan en La Bisbal del Ampurdán, Gerona, donde adquieren una granja de pollos.",
 'text2b': "El sueño de Cugat era convertirse en un gran concertista clásico. No lo consiguió, pero sí realizó el llamado ‘sueño americano’.",
 'text3': "“En esa época, en Tijuana, en la frontera entre México y California, alcanzó una gran fama un club nocturno que también era casino e hipódromo. Allí, yo me encargaba del espectáculo principal. Había una pareja artística que pronto atrajo la atención del público: estaba compuesta, curiosamente, por un padre y su hija, excelentes bailarines españoles. La hija se llamaba Margarita, tenía 17 años y unas formas proporcionadas y armónicas“.",
 'text4': "En 1946, Cugat gana un millón de dólares como director de orquesta, en aquel momento el caché más alto pagado para un puesto como el suyo. Actualmente, equivaldría a recibir 12 millones de dólares.",
 'text5': "'Divorciado de Lorraine Allen, necesitaba una nueva compañera, tanto para mi vida privada como para mi espectáculo. Buscando a una muchacha que cumpliera con los requisitos necesarios, fui a Nueva York a ver ‘Botton shoes’,  el espectáculo producido por el exmarido de Liz Taylor, el productor Michael Todd. En el coro había 16 chicas bailando, todas muy bellas y parecidas entre sí. Pero vi que la quinta por la izquierda tenía un ‘no sé qué’ distintio, así que quise conocerla e hice que me la presentaran. [...] Se llamaba Abbe Lane. En 1950 nos casamos y fuimos felices durante 15 años de matrimonio'."
},
'text': {
 'mainTitle': "SEXO, MARACAS Y CHIHUAHUAS",
 'mainSubtitle': "La increíble vida de",
 'name': "Xavier Cugat",
 'instructionAnecdota': "Haz clic cuando veas aparecer al chihuahua, podrás conocer todo tipo de anécdotas curiosas acerca de Cugui",
 'instructionPentagram': "Haz click sobre las notas musicales para recorrer la vida de Xavier, desde su infancia hasta su vejez",
 'instructionLastVideos': "Haz scroll para descubrir más vídeos sobre Xavier Cugat del fondo documental de RTVE",
 'instructionInfo': "Haz clic aquí para conocer más detalles sobre un momento en particular de la vida de Cugat",
 'mobileDisclaimer': "Lo sentimos, este documental interactivo no está diseñado para dispositivos móviles. Disfruta mejor del univeso de Xavier Cugat desde tu ordenador o tablet. ¡Te esperamos!",
 'texto11': "Xavier Cugat nace en Gerona el 1 de enero de 1900.",
 'text1': "Entre 1915 y 1918  lidera su primera formación musical y empieza su periplo amoroso con su primera mujer: RITA MONTANER",
 'text2': "En el año 1945, Cugat y Frank Sinatra graban un sencillo y dos boleros lentos: 'My Shawl' y 'Stars in your eyes'.",
 'text4': "Cugat se lleva a Charo a trabajar a los Estados Unidos y, finalmente, se casa con ella en 1966. Sería su quinto y último matrimonio.",
 'text5': "En 1954, Cugat debuta con su orquesta en la Plaza Monumental de Barcelona.",
 'text6': "¿Descubridor de Rita Hayworth?",
 'text7': "En 1971, Cugat regresa a Cataluña. Su proyecto era tener una casa-estudio en la Costa Brava para poder contemplar el mar y dibujar.",
 'textoFin': "Cugat fallece en Barcelona el 27 de octubre de 1990."
}
};
